language: node_js
cache: yarn
sudo: required
env:
  - SPEC_PATH=$(pwd)
services:
  - docker
before_install:
  - docker pull slate/swagger-spec-validator
  - docker run -it -e "SPEC_PATH=$SPEC_PATH" -v $SPEC_PATH:/data --name spec-validator slate/swagger-spec-validator:latest
script: docker logs $(docker ps -lq)
notifications:
  slack:
    secure: rf/kaNKQb7DXyS16schfpDbxTgf6OyA5kqv8V08wot7HwEWuGkVpz4bfm2dHYdqXCIJYbEG5zCl8stjTAL3ppuD0i02Ej3JKCzgpNvPrvYwtE+yM4qDXSXjpp8xkVxo/uGtvtaFBFckW84JtbRUU/FGZm2xaMPILIQ1+Zy1Xw9pEj6B39cYyTx9EXEqE5yHlv9O67JHO7ihZy3jyDMiOd+WBLw2Ne16lqbGwMan3AhKyg1sfoc15uwVzumSKGXPTnrKVo4RqQHaj7+crDvqTTx2fpAFjhrPWatcZw8m77f/47yF5en660Fbq/msJ134FHgAr1hxdIGFf9EbvFmSDJR86fPlnfNrtJPbpYzn4i7dYgLnUVwm5oxt1tW5e3ytPCwXEYqx87/OyZDucXYWQbgefkg2+0sWU2UxdWpOBEPkLMtcr8Mq56EUkDltsRgl4Qvi6DTc5tpZOOHLaCwMijPwlJf1RKSiY5D0z32v4mJwOPkjjk36SkJ+/HVZQT0qmkwVKUy2Ft/8saX4vX6MtlYpk8RJtII1/se6f37EdbnYXMfqTf2YoVbc7RyFA48ECfcb10mk4nM5yt9jGfCIUehrR5sPNKHH7I3up9doV8QZROyNf300QFwoxJKD8ZMo4sjqXk1SKxgMjZX903U0XITTvPveMhRcIl3zVcDoEkdE=
